update update_cd_repo be

diff --git a/.github/workflows/docker-build-be.yml b/.github/workflows/docker-build-be.yml
--- a/.github/workflows/docker-build-be.yml
+++ b/.github/workflows/docker-build-be.yml
@@ -69,9 +69,53 @@ jobs:
       - name: Build and Push Docker image
         uses: docker/build-push-action@v6
         with:
-          context: ./client
-          file: ./client/Dockerfile
+          context: ./api
+          file: ./api/Dockerfile
           push: true
           tags: |
             hovietvinh29032004/backend:latest
             hovietvinh29032004/backend:${{ env.IMAGE_TAG }}
+      
+  update_cd_repo:
+    runs-on: ubunbtu-latest
+    needs: [build_backend_docker_image_and_push, resolve_env]
+    environment: ${{needs.resolve_env.outputs.environment}}
+    env:
+      CD_REPO_TOKEN: ${{ secrets.CD_REPO_TOKEN }}
+    steps:
+      - name: Checkout CD repo
+        uses: actions/checkout@v4
+
+        with:
+          repository: hovietvinh/3-Tier-GitOps-CD
+          ref: dev
+          token: ${{ env.CD_REPO_TOKEN }}
+          path: cd
+      
+      - name: Bump images in manifests (safe)
+        working-directory: cd
+        env:
+          IMAGE_TAG: ${{ env.IMAGE_TAG }}
+        run: |
+          curl -sL https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o yq && sudo install yq /usr/local/bin/yq
+
+          # -- Safety cleanup: remove any accidental .spec.template from Service docs
+          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' k8s/backend.yaml
+          yq -i '(. | select(.kind=="Service")) |= del(.spec.template)' k8s/frontend.yaml
+
+          # -- Update ONLY Deployment images (backend)
+          yq -i '
+            (. | select(.kind=="Deployment")
+               | .spec.template.spec.containers[]
+               | select(.name=="backend-deployment")
+               | .image)
+            = "hovietvinh29032004/backend:" + strenv(IMAGE_TAG)
+          ' k8s/backend.yaml
+      - name: Commit & push to CD repo
+        working-directory: cd
+        run: |
+          git config user.name "ci-bot"
+          git config user.email "ci-bot@users.noreply.github.com"
+          git add -A
+          git commit -m "bump images to ${IMAGE_TAG}" || echo "no changes"
+          git push
